server:
  port: 9020

gcp:
  project-id: red-welder-466202-u6
  key:
    path: C:/Users/Ramu/Documents/Ramu/LTC/Hackathon/Reboot/sa-key.json

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false